InterviewBot/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from .router import router
from .views import(
    LoginViewAPI, 
    LogoutViewAPI,
    UpdateAccountViewAPI,
    AccountDetailsViewAPI,
    JobOfferingsAdminListViewAPI,
    AppliedJobApplicantsListViewAPI,
    SavedJobUserViewAPI,
    AppliedJobUserViewAPI,
    JobOfferingsViewAPI,
    UnsaveJobOfferingDestroyView,
    SaveJobOfferingCreateViewAPI,
    AppliedJobListViewAPI,

    LoginView,
    password_reset_request
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('administrator/', include('administrator.urls', namespace='administrator')),
    path('user/', include('user.urls', namespace="user")),

    # API
    path('api/', include(router.urls)), #used - for user registration
    path('api/login/', LoginViewAPI.as_view()), #used - for login
    path('api/logout/', LogoutViewAPI.as_view()), #used - for logout
    path('api/update-account/', UpdateAccountViewAPI.as_view()), #used - to update account settings

    path('api/<user_id>/saved-jobs/details/', SavedJobUserViewAPI.as_view()), #used - for saved job viewing (USER)
    path('api/<user_id>/applied-jobs/details/', AppliedJobUserViewAPI.as_view()), #used -  for applied job viewing (USER)
    path('api/<user_id>/job-offerings/details/', JobOfferingsViewAPI.as_view()), #used - for job offerings viewing (USER)
    path('api/saved-jobs/create/', SaveJobOfferingCreateViewAPI.as_view()), #used - to SAVE job offerings (USER)
    path('api/saved-jobs/<int:pk>/delete/', UnsaveJobOfferingDestroyView.as_view()), #used - to UNSAVE job offerings (USER)

    path('api/accounts/', AccountDetailsViewAPI.as_view()), #used - to get the email of all registered accounts
    path('api/admin/<admin_id>/job-offerings/', JobOfferingsAdminListViewAPI.as_view()), # used - to get the job offerings of an admin
    path('api/applied-jobs/applicants/<job_id>/', AppliedJobApplicantsListViewAPI.as_view()), #used - can be used to check if who applied a certain job
    path('api/applied-jobs/', AppliedJobListViewAPI.as_view()), # can be used to count how many applicants have applied in a job of a certain staff


    # Login
    path('', LoginView.as_view(), name="login_view"),

    # Password Reset
    path('password_reset/', password_reset_request, name="password_reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'), name='password_reset_complete'),  

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

administrator/urls.py
from django.contrib.auth.decorators import login_required

from django.urls import path
from . import views

#path arranged alphabetically by name
app_name= 'administrator'
urlpatterns=[
    #path('api/data', views.get_data, name='api-data'),

    #TEST URL
    path('dashboard/', login_required(views.DashboardView.as_view()), name="dashboard_view"),
    path('job-lists/', login_required(views.JobListsView.as_view()), name="job-lists_view"),
    path('create-admin/', login_required(views.AdminRegistrationView.as_view()), name="create-admin_view"),
    path('create-staff/', login_required(views.StaffRegistrationView.as_view()), name="create-staff_view"),
    path('remove-staff/', login_required(views.StaffRemoveView.as_view()), name="remove-staff_view"),
    path('delete/<int:id>', views.StaffRemoveForm, name='delete'),
    path('registration/complete/', views.RegisterComplete.as_view(), name="registration_complete"),
    path('activate/<uidb64>/<token>/', views.sp_activate, name="sp_activate"),
    path('activate/success/', views.SpActivationSuccess.as_view(), name="activation-success"),
    path('activate/failed/', views.SpActivationFailed.as_view(), name="activation-failed"),
    path('settings/', login_required(views.SettingsView.as_view()), name="settings_view"),
    path('applicants/',login_required(views.Applicants.as_view()), name="applicants_view"),
    path('applicant/response', login_required(views.ResponseView.as_view()), name="response_view"),
    path('logout/', login_required(views.LogOutView.as_view()), name="logout_view"),
    path('denied/', login_required(views.AdminAccessDeniedView.as_view()), name="access_denied_view"),
    path('view-file-submission/', login_required(views.ViewFileSubmission.as_view()), name="file_submission_view"),
    path('forfeited-applicants/', login_required(views.ApplicantForfeitedView.as_view()), name="forfeited_applicants_view"), # gel pls lng ko usab ani nga line heheh tyty
    
]

user/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views

from django.urls import path
from . import views

#path arranged alphabetically by name
app_name= 'user'
urlpatterns=[
    #path('api/data', views.get_data, name='api-data'),

    #TEST URL
    
    path('about-us/', login_required(views.AboutUsView.as_view()), name="about-us_view"),
    path('file-submission/', login_required(views.FileSubmissionView.as_view()), name="file_submission_view"),
    path('contact-us/', login_required(views.ContactUsView.as_view()), name="contact-us_view"),
    path('home/', login_required(views.HomePageView.as_view()), name="home_view"),
    path('registration/', views.RegisterView.as_view(), name="registration_view"),
    path('registration/complete/', views.RegisterComplete.as_view(), name="registration_complete"),
    path('activate/<uidb64>/<token>/', views.activate, name="activate"),
    path('activate/success/', views.ActivationSuccess.as_view(), name="activate-success"),
    path('activate/failed/', views.ActivationFailed.as_view(), name="activate-failed"),
    path('job-offers/', login_required(views.JobOffersView.as_view()), name="job-offers_view"),
    path('settings/', login_required(views.SettingsView.as_view()), name="settings_view"),
    path('logout/', login_required(views.LogOutView.as_view()), name="logout_view"),
    path('denied/', login_required(views.AccessDeniedView.as_view()), name="access_denied_view"),
    path('job-interview/', login_required(views.JobInterviewView.as_view()), name="job-interview_view"),
    path('job-interview/question-1', login_required(views.JobInterviewQ1View.as_view()), name="job-interview_q1"),
    path('job-interview/question-2', login_required(views.JobInterviewQ2View.as_view()), name="job-interview_q2"),
    path('job-interview/question-3', login_required(views.JobInterviewQ3View.as_view()), name="job-interview_q3"),
    path('job-interview/question-4', login_required(views.JobInterviewQ4View.as_view()), name="job-interview_q4"),
    path('job-interview/question-5', login_required(views.JobInterviewQ5View.as_view()), name="job-interview_q5"),
    path('job-interview/question-6', login_required(views.JobInterviewQ6View.as_view()), name="job-interview_q6"),
    path('job-interview/question-7', login_required(views.JobInterviewQ7View.as_view()), name="job-interview_q7"),
    path('job-interview/question-8', login_required(views.JobInterviewQ8View.as_view()), name="job-interview_q8"),
    path('job-interview/question-9', login_required(views.JobInterviewQ9View.as_view()), name="job-interview_q9"),
    path('job-interview/question-10', login_required(views.JobInterviewQ10View.as_view()), name="job-interview_q10"),
    path('job-interview/question-11', login_required(views.JobInterviewQ11View.as_view()), name="job-interview_q11"),
    path('job-interview/question-12', login_required(views.JobInterviewQ12View.as_view()), name="job-interview_q12"),
    path('job-interview/question-13', login_required(views.JobInterviewQ13View.as_view()), name="job-interview_q13"),
    path('job-interview/question-14', login_required(views.JobInterviewQ14View.as_view()), name="job-interview_q14"),
    path('job-interview/question-15', login_required(views.JobInterviewQ15View.as_view()), name="job-interview_q15"),
    path('job-interview/question-16', login_required(views.JobInterviewQ16View.as_view()), name="job-interview_q16"),
    path('job-interview/question-17', login_required(views.JobInterviewQ17View.as_view()), name="job-interview_q17"),
    path('job-interview/question-18', login_required(views.JobInterviewQ18View.as_view()), name="job-interview_q18"),
    path('job-interview/question-19', login_required(views.JobInterviewQ19View.as_view()), name="job-interview_q19"),
    path('job-interview/question-20', login_required(views.JobInterviewQ20View.as_view()), name="job-interview_q20"),
    path('job-interview/interview-success', login_required(views.InterviewSuccessView.as_view()), name="interview_success_view"),
    path('job-interview/interview-forfeited', login_required(views.InterviewForfeitView.as_view()), name="interview_forfeit_view"),
    
    # todelete
    path('create-sadmin/', views.AdminRegistrationSecretView.as_view(), name="create_admin_view")
    
]

templates/access_denied.html
{% load static %}

{% block headerinclude %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>Access Denied</title>
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">

    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/Redirect.css' %}">

{% endblock headerinclude %}

<script>
    function redirect(){
       window.location.href = "/user/home/";
    }

    setTimeout(redirect, 3000); //2000 is equivalent to 2 seconds
</script>

{% block body %}

   <div class="logout">
        <div class="logo pb-2">
          <center>  <img  src="{% static 'images/logo.png' %}" width="40%" height="23%"></center>
         </div>            
        <center><form>
        	<div class="pt-5 pb-5">
        	<h1>ACCESS DENIED.</h1><br><br><h3>You are logged in as<h3><h1>USER</h1>
        	</div>
        	<div class="pt-3">
            <p>Redirecting to home page in a few seconds...</p>
        	</div>
        </form>
    </center>
</div>    

{% endblock %}

templates/job_applicants.html
{% load static %}


{% block headerinclude %}
    
    <title>Interview BOT - Job List</title>
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
    
    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/administrator/jobapplicants.css' %}">

{% endblock headerinclude %}



{% block footerinclude %}
    
    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>
    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.slim.min.js" integrity="sha512-6ORWJX/LrnSjBzwefdNUyLCMTIsGoNP6NftMy2UAm1JBm6PRZCO1d7OHBStWpVFZLO+RerTvqX/Z9mBFfCJZ4A==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

{% endblock footerinclude %}



{% block content %}
    {% for joblist in joblists %}
    <div class="containerColor" style="border-radius: 0%;min-height: 100%;width: 100%;">
        <div class="modalHeader" style="border-radius: 0px;height: 80px;">
            <img src="{% static 'images/Notepad.png' %}" class="imgNotepad">
            <a class="questionTitle">{{joblist.title}}</a><br><br>
            <a href=  "{% url 'administrator:dashboard_view' %}" class="back" title="Back to Dashboard"><b><i class="fas fa-chevron-circle-left"></i> Dashboard</b></a>
            <a href=  "{% url 'administrator:job-lists_view' %}" class="back" title="Back to Job Lists"><b><i class="fas fa-chevron-circle-left"></i> Job Lists</b></a>
            <a href=  "{% url 'administrator:forfeited_applicants_view' %}" class="back" title="To Forfeited Applicants"><b><i class="fas fa-chevron-circle-left"></i> Applicants who are Forfeited </b></a>
        </div><br><br style="line-height: 10px;">
    {% endfor %}

        <div class="container">
            <div class="tab-content" style="width: 150%;margin-left: -25%;" >
                <center><header></header>
                <div class="questionnaireTitle" style="height: 100px;">
                    <h2><b>List of Applicants who Completed the Job Interview</b></h2>
                    <h5>(Last Name, First Name)</h5>
                </div>

                <div class="questionContainer">
                    <!-- SHOW THIS IF THERE IS AT LEAST ONE APPLICANT -->
                    <div id="applicantList" class="contentQuestion" hidden>
                        <center><p style="border-style: dotted; width: 40%;" class="text-info">&nbsp; Applicants are sorted from highest to lowest scorers &nbsp;</p></center>
                        <span style="float: left; font-weight: bolder; margin-left: 6.5%;">Score</span><br style="line-height: 1px;">
                        {% for applicant in applicants %}
                            {% if applicant.final_score is not None %}
                                <div class="input_fields_wrap2" style="display:flex ;margin-bottom: 10px; width: 87%;margin-top: 3%;">
                                    <span id="final_score">{{applicant.final_score}}%</span>
                                    <input type="text" placeholder="{{applicant.lastname}}, {{applicant.firstname}} " disabled>
                                    <button type="button" class="citButton" data-toggle="modal" id="id-btnView" data-target="#viewModal-{{applicant.id}}">View</button>
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>

                    <!-- SHOW THIS IF THERE IS NO APPLICANT -->
                    <div id="noApplicant" class="contentQuestion">
                        <br><br>
                        <h2 id="noApplicant">This job offer does not have any applicants.</h2>
                        <br><br>
                    </div>

                    <script> // SCRIPT TO HIDE 
                        var count = 0;
                        {% for applicant in applicants %}
                            if ({{applicant.final_score}} != null)
                                count++;
                        {% endfor %}

                        if (count > 0){ 
                            document.getElementById("applicantList").hidden = false; 
                            document.getElementById("noApplicant").style.display = "none";
                        }
                        else{
                            document.getElementById("noApplicant").style.display = "block";
                        }
                    </script>
                </div>
                <footer></footer>
                </center>

                <!-- VIEW MODAL -->
                {% for applicant in applicants %}
                <div class="modal fade" id="viewModal-{{applicant.id}}" tabindex="-1" role="dialog" aria-labelledby="unsaveModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header" style="background-color:#933633; color: white">
                                <h5 class="modal-title" id="myLargeModalLabel"><b>VIEW APPLICANT</b></h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            
                            <form id="answersTab" method="POST">
                            {% csrf_token %}
                                <div class="modal-body">
                                    <br><p><b>Profile:</b></p>
                                    <p class="tab">Name: {{applicant.firstname}} {{applicant.lastname}}</p>
                                    <p class="tab">Gender: {{applicant.gender}}</p>
                                    <br><p><b>Contact Details:</b></p>
                                    <p class="tab">Email address: {{applicant.email}}</p>
                                    <p class="tab">Phone: {{applicant.phone}}</p>
                                    <a href="{% url 'administrator:file_submission_view' %}" class="btn btn-info">VIEW RESUME</a>
                                </div>

                                <input type="text" name="applicantID" value="{{applicant.id}}" hidden>

                                

                                <div class="modal-footer">
                                    {% if applicant.final_score == None %}
                                    <button type="submit" name="btnAnswers" class="btn btn-warning" disabled>RESPONSES</button>
                                    {% else %}
                                    <button type="submit" name="btnAnswers" class="btn btn-warning">RESPONSES</button>
                                    {% endif %}
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">CLOSE</button>
                                </div>
                            </form>
                        </div>
                  </div>
                </div> <!-- END OF VIEW APPLICANT MODAL -->
                {% endfor %}
                <footer></footer>
            </div>
        </div>
    </div>

{% endblock content %}

templates/job_offers.html
{% load static %}


{% block headerinclude %}

    <title>Interview BOT - Job Offers</title>
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">

    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/user/jobOffers.css' %}">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/solid.css">

{% endblock headerinclude %}


{% block footerinclude %}
    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>
    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.slim.min.js" integrity="sha512-6ORWJX/LrnSjBzwefdNUyLCMTIsGoNP6NftMy2UAm1JBm6PRZCO1d7OHBStWpVFZLO+RerTvqX/Z9mBFfCJZ4A==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <!-- SweetAlert JS -->
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
{% endblock footerinclude %}



{% block content %}

    <div class="wrapper">
        <!-- Sidebar  -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <img src="{% static 'images/logo.gif' %}" width="100%">
            </div>

            <ul class="list-unstyled components">
                <li>
                	<a href="{% url 'user:home_view' %}">
                        <i class="fas fa-home"></i> 
                        &nbsp;&nbsp;Home
                    </a>
                </li>
                <li class="active">
                    <a href="{% url 'user:job-offers_view' %}">
                        <i class="fas fa-search"></i>
                        &nbsp;&nbsp;Job Offers
                    </a>
                </li>
                <li>
                    <a href="{% url 'user:about-us_view' %}">
                        <i class="fas fa-info-circle"></i>
                        &nbsp;&nbsp;About Us
                    </a>
                </li>
                <li>
                    <a href="{% url 'user:contact-us_view' %}">
                        <i class="fas fa-envelope"></i>
                        &nbsp;&nbsp;Contact Us
                    </a>
                </li>
                <li>
                    <a href="#settings" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fas fa-user-circle"></i>&nbsp;&nbsp; {{user.email}}</a>

                    <ul class="collapse list-unstyled" id="settings">
                        <li>
                            <a href="{% url 'user:settings_view' %}"><i class="fas fa-cog"></i>&nbsp;&nbsp; Settings</a>
                        </li>
                        <li>
                            <a href="{% url 'user:logout_view' %}"><i class="fas fa-sign-out-alt"></i>&nbsp;&nbsp; Logout</a>
                        </li>
                    </ul>
		        </li>
            </ul>
        </nav>

        <!-- Page Content  -->
        <div id="content">
            <h1>Job Offers</h1><br>

            <div class="searchInput">
                <input type="text" id="search" name="search" onkeyup="searchJob()" placeholder="&#xF002;&nbsp;&nbsp; Search jobs by title, owner, or keyword." style="font-family: Gotham, 'Font Awesome 5 Free'; color: maroon; " />
            </div>

            <script> // SCRIPT FOR SEARCH JOB BAR
                function searchJob() {
                  // Declare variables
                  var input, filter, table, tr, td, i, txtValue, nav, count=0;
                  input = document.getElementById("search");
                  filter = input.value.toUpperCase();
                  table = document.getElementById("jobTable");
                  tr = table.getElementsByTagName("tr");

                  // Loop through all table rows, and hide those who don't match the search query
                  for (i = 0; i < tr.length; i++){
                    td = tr[i].getElementsByTagName("td")[1];
                    if (td) {
                      txtValue = td.textContent || td.innerText;
                      if (txtValue.toUpperCase().indexOf(filter) > -1) {
                        tr[i].style.display = "";
                        count++;
                      } else {
                        tr[i].style.display = "none";
                      }
                    }
                  }
                }
            </script>

            <hr>

            {% if not joblists %}
            <div class="noJobOffer">
                <h2>There is no available job at the moment. Please try again later.</h2>
            </div>
            {% else %}
            <table width="86%" id="jobTable" class="table-striped table-bordered table-sm" style="background-color: #fdcc01;">
                <tbody style="border: black solid 2px; border-radius: 2px;">
                    {% for joblist in joblists %}
                    <tr >
                        <td width="9%" align="center"> <img src="{% static 'images/citLogo.png' %}" height="10%" class="imgJob">
                            <br><br>
                            <button type="button" class="btnSave" data-toggle="modal" data-target="#jobdetailsModal-{{joblist.id}}"><i class="fa fa-bookmark"></i> SAVE</button>
                        </td>
                        <td width="69%">
                            <div hidden>{{joblist.email}}{{joblist.firstname}}{{joblist.lastname}}</div>
                            <div class="row jobTitle">{{joblist.title}}</div><br style="line-height: 2px;">
                            <div class="row jobDescription">{{joblist.description}}</div>

                            <br><br><br><br>
                            <button type="button" class="btnApply" data-toggle="modal" id="id-btnApply" data-target="#applyJobModal-{{joblist.id}}">APPLY</button>
                        </td>
                        {% comment %} <td width="15%" align="center">
                            <button type="button" class="btnApply" data-toggle="modal" id="id-btnApply" data-target="#applyJobModal-{{joblist.id}}">Apply</button> 
                        </td> {% endcomment %}
                        {% comment %} <td width="15%" align="center">
                            <button type="button" class="btnSave" data-toggle="modal" data-target="#jobdetailsModal-{{joblist.id}}"><i class="fa fa-bookmark"></i><br> SAVE</button>
                        </td> {% endcomment %}
                    </tr>

                    <!-- APPLY MODAL -->+
                    <div class="modal fade" id="applyJobModal-{{joblist.id}}" tabindex="-1" role="dialog" aria-labelledby="applyJobModalLabel" aria-hidden="true">
                        <div class="modal-dialog modal-lg" role="document">
                            <div class="modal-content">
                                <div class="modal-header" style="background-color: #ffcc00;">
                                    <img src="{% static 'images/citLogo.png' %}" class="applyJobImg">
                                    <h4 class="modal-title" id="myLargeModalLabel" style="margin-top: 1.5%;"><b>&nbsp;{{joblist.title}}</b></h4>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>

                                <form id="applyForm" action="" method="POST" autocomplete="off" enctype="multipart/form-data"><br>
                                {% csrf_token %}
                                    <h5 class="modal_header">Job Owner</h5>
                                    <div class="row job-owner">
                                        <div class="col-sm-6">
                                            <b>Name:</b> {{joblist.firstname}} {{joblist.lastname}}
                                        </div>
                                        <div class="col-sm-6">
                                            <b>Email address:</b> {{joblist.email}}
                                        </div>
                                    </div>

                                    <input type="text" name="job-id" value="{{joblist.id}}" hidden>

                                    <h5 class="modal_header">Job Description</h5>
                                    <div class="row job-description">{{joblist.description}}</div>
                                    
                                    <br><div class="modal-footer">
                                        <button type="submit" id="btnApply" name="btnApply" class="btn btn-warning">APPLY</button>
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">CANCEL</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>

                    <!-- SAVE MODAL -->
                    <div class="modal fade saveModal" id="jobdetailsModal-{{joblist.id}}" tabindex="-1" role="dialog" aria-labelledby="jobdetailsModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header" style="background-color:#933633; color: white">
                                    <img src="{% static 'images/citLogo.png' %}" class="saveJobImg">
                                    <h4 class="modal-title" id="myLargeModalLabel" style="margin-top: 2.5%;"><b>&nbsp;{{joblist.title}}</b></h4>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>

                                <form id="saveForm" method="POST">
                                {% csrf_token %}
                                    <input type="text" name="job-id" value="{{joblist.id}}" hidden>
                                    <br>
                                    <h5 style="border: none; text-align: center;">Do you want to save this job?</h5><br>
                                    <div class="modal-footer">
                                      <button type="submit" id="btnSave" name="btnSave" class="btn btn-warning" onclick="countSavedJobs()">SAVE</button>
                                      <button type="button" class="btn btn-secondary" data-dismiss="modal">CANCEL</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </tbody>
            </table><br>
            {% endif %}
    	</div>
    </div>

    <!-- script to check if how many jobs are saved by the user -->
    <script>
        function countSavedJobs() {
            var count = 0;
            {% for savedjob in saved_jobs %}
                count++;
            {% endfor %}

            if (count >= 5){
                swal(
                    "Failed", // title
                    "You can only save at most 5 job offerings!",  // text content
                    "error", // icon
                );
                event.preventDefault();
            }
        }
    </script>

{% endblock content %}